apiVersion: batch/v1
kind: CronJob
metadata:
  name: edge-node-updater-cronjob
  namespace: default
spec:
  # Run every 1 minutes. See https://en.wikipedia.org/wiki/Cron
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: updater
            image: registry.suse.com/bci/bci-base:15.4
            command:
            - /bin/bash
            - -c
            - /opt/updater/updater.sh
            volumeMounts:
            - name: config-volume
              mountPath: /opt/updater
          volumes:
            - name: config-volume
              configMap:
                defaultMode: 0740
                name: edge-node-updater-configmap
          restartPolicy: OnFailure
