= Installation Instructions for RKE2 on SUSE Linux Enterprise
:toc: macro
:toclevels: 2
:sectanchors:

== Overview

This installation assumes running on SUSE Linux Enterprise and using a TLS cert issued by a public CA, such as Let's Encrypt. Some small adjustments will have to be made if not meeting these two expectations.

== System Update

```bash
sudo zypper -n up
```
(for SLE Micro use `transactional-update up`)

```bash
sudo reboot
```

== Environment Setup

```bash
echo "export KUBECONFIG=/etc/rancher/rke2/rke2.yaml" >> ${HOME}/.bashrc
echo "PATH=${PATH}:/opt/rke2/bin:/var/lib/rancher/rke2/bin/" >> ${HOME}/.bashrc && source  ${HOME}/.bashrc
```

```bash
sudo mkdir -p /etc/rancher/rke2/
```

// Enter your FQDN within the quotes
.FQDN
```
FQDN=""
```

== DNS Check

```bash
nslookup ${FQDN}   # Should show the public IP associated with the FQDN
```

== Configuration

```bash
sudo bash -c "cat <<EOF > /etc/rancher/rke2/config.yaml
write-kubeconfig-mode: "0644"
token: RKE2-HA-4-Me
tls-san:
  - "${FQDN}"
EOF"
```

```bash
cat /etc/rancher/rke2/config.yaml
```

== RKE2 Release

Pick a release of RKE2 from: https://github.com/rancher/rke2/releases

```bash
export RKE2_RELEASE=""
```

== Installation of RKE2

```bash
sudo bash -c "curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION="${RKE2_RELEASE}" sh -"
```

```bash
sudo systemctl enable --now rke2-server.service
```

```bash
mkdir -p ${HOME}/.kube
```

```bash
sudo cp /etc/rancher/rke2/rke2.yaml ${HOME}/.kube/config
sudo chown -R ${USER} ${HOME}/.kube/
```
```bash
echo "export KUBECONFIG=${HOME}/.kube/config" >> ${HOME}/.bashrc
```

```bash
source ${HOME}/.bashrc
```

Verify RKE2 is installed and running correctly:

```bash
watch -c kubectl get pods -A
```

== Post-Installation

Continue after RKE2 is installed and running correctly.

=== Adding Nodes (Optional)

```bash
sudo zypper -n up
```
(for SLE Micro use `transactional-update up`)

```bash
sudo reboot
```

```bash
sudo mkdir -p /etc/rancher/rke2/
```

```bash
export FIRST_RKE2_NODE=""
```

```bash
sudo bash -c "cat <<EOF > /etc/rancher/rke2/config.yaml
write-kubeconfig-mode: "0644"
token: RKE2-HA-4-Me
server: https://${FIRST_RKE2_NODE}:9345
EOF"
```

```bash
export RKE2_RELEASE=""
```

==== Server (Control-Plane) Nodes

```bash
sudo bash -c "curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION="${RKE2_RELEASE}" INSTALL_RKE2_TYPE="server" sh -"
```

```bash
sudo systemctl enable --now rke2-server.service
```

==== Agent (Worker) Nodes

```bash
sudo bash -c "curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION="${RKE2_RELEASE}" INSTALL_RKE2_TYPE="agent" sh -"
```

```bash
sudo systemctl enable --now rke2-agent.service
```

= Install Rancher Server

== Install Helm

```bash
sudo zypper -n in helm
```

IMPORTANT: Select only one of "External (Bring Your Own) Certificates" OR "Rancher-generated TLS certificates" for TLS certificate management appropriate for your installation. See https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster#3-choose-your-ssl-configuration for more information.

=== External (Bring Your Own) Certificates:

. The following commands assume the public TLS certificate, normally named `fullchain.pem`, exists in the local directory as `tls.crt`, and the associated private key, normally named `privkey.pem`, exists in the local directory as `tls.key`.

. Examine the TLS cert, if desired:

```bash
openssl x509 -noout --text -in tls.crt | less
```

. Create the secret containing the certificate and key:

```bash
kubectl -n cattle-system create secret tls tls-rancher-ingress \
  --cert=tls.crt \
  --key=tls.key
```

// Note that helm is only available (AFAICT) in PackageHub and software.opensuse.org

// source /etc/os-release
// sudo SUSEConnect -p PackageHub/${VERSION_ID}/x86_64

=== Rancher-generated TLS certificates:

. Add the Jetstack Helm repository:

```bash
helm repo add jetstack https://charts.jetstack.io
```

. Update your local Helm chart repository cache

```bash
helm repo update
```

. Install the cert-manager Helm chart:

```bash
helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --set crds.enabled=true
```

. Verify the cert-manager installation:

```bash
kubectl get pods --namespace cert-manager
```

== Install the Rancher Helm chart:

NOTE: Adjust the following command to use the `rancher-stable` or `rancher-alpha` repos, if you prefer:

```bash
helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
```

. Update your local Helm chart repository cache

```bash
helm repo update
```

== Set the Bootstrap Password

```bash
BOOTSTRAPPW="Rancher4Me"  
```

Find the version of Rancher you want to install:

```bash
helm search repo rancher-latest --versions | more
```

```bash
RANCHER_CHART_VERSION=""    # CHART VERSION not APP VERSION
SET_DEVEL_FLAG=""     # Set to --devel for access to development features
TLS_SOURCE=""         # Leave blank for Rancher Certificates, set to "--set ingress.tls.source=secret" if using External (BYO) Certificates
```

Verify the variables before running the helm installation:

```bash
echo "RANCHER_CHART_VERSION="${RANCHER_CHART_VERSION}; echo "SET_DEVEL_FLAG="${SET_DEVEL_FLAG}; echo "FQDN="${FQDN}; echo "TLS_SOURCE="${TLS_SOURCE}; echo "BOOTSTRAPPW="${BOOTSTRAPPW}
```

== Install Rancher with Helm

```bash
kubectl create namespace cattle-system
```

```bash
helm install rancher rancher-latest/rancher --version ${RANCHER_CHART_VERSION} ${SET_DEVEL_FLAG} \
  --namespace cattle-system \
  --set hostname=${FQDN} \
    ${TLS_SOURCE} \
  --set bootstrapPassword=${BOOTSTRAPPW}

```

// Rancher server consists of two deployments, rancher and rancher-webhook

```bash
watch -c kubectl -n cattle-system get deploy
```

Log into the Rancher web UI at ${FQDN} and the user `admin` with a password of ${BOOTSTRAPPW}.

== Just Installing RKE2

=== First Node

```bash
export RKE2_RELEASE="v1.30.2+rke2r1"
```

```bash
echo "export KUBECONFIG=/etc/rancher/rke2/rke2.yaml" >> ${HOME}/.bashrc
echo "PATH=${PATH}:/opt/rke2/bin:/var/lib/rancher/rke2/bin/" >> ${HOME}/.bashrc && source  ${HOME}/.bashrc
```

```bash
sudo mkdir -p /etc/rancher/rke2/
```

```bash
sudo bash -c "cat <<EOF > /etc/rancher/rke2/config.yaml
write-kubeconfig-mode: "0644"
token: RKE2-HA-4-Me
EOF"
```

```bash
sudo bash -c "curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION="${RKE2_RELEASE}" sh -"
```

```bash
sudo systemctl enable --now rke2-server.service
```

```bash
mkdir -p ${HOME}/.kube
```

```bash
sudo cp /etc/rancher/rke2/rke2.yaml ${HOME}/.kube/config
sudo chown -R ${USER} ${HOME}/.kube/
echo "export KUBECONFIG=${HOME}/.kube/config" >> ${HOME}/.bashrc
source ${HOME}/.bashrc
```

=== Servers

```bash
export RKE2_RELEASE="v1.30.2+rke2r1"
export FIRST_RKE2_NODE=""
```

```bash
sudo mkdir -p /etc/rancher/rke2/
```

```bash
sudo bash -c "cat <<EOF > /etc/rancher/rke2/config.yaml
write-kubeconfig-mode: "0644"
server: https://${FIRST_RKE2_NODE}:9345
token: RKE2-HA-4-Me
EOF"
```

```bash
sudo bash -c "curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION="${RKE2_RELEASE}" INSTALL_RKE2_TYPE="server" sh -"
```

```bash
sudo systemctl enable --now rke2-server.service
```

=== Agents

```bash
export RKE2_RELEASE="v1.30.2+rke2r1"
export FIRST_RKE2_NODE=""
```

```bash
sudo mkdir -p /etc/rancher/rke2/
```

```bash
sudo bash -c "cat <<EOF > /etc/rancher/rke2/config.yaml
write-kubeconfig-mode: "0644"
server: https://${FIRST_RKE2_NODE}:9345
token: RKE2-HA-4-Me
EOF"
```

```bash
sudo bash -c "curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION="${RKE2_RELEASE}" INSTALL_RKE2_TYPE="agent" sh -"
```

```bash
sudo systemctl enable --now rke2-agent.service
```
