apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: aerospike-cluster-2
  region: us-west-2
  version: "1.19"

managedNodeGroups:
  - name: ng-1
    instanceType: t3a.medium
    desiredCapacity: 3
    volumeSize: 20
    ssh:
      allow: true 
    privateNetworking: false
    additionalVolumes:
      - volumeName: '/tmp/mount-1' # required
        volumeSize: 80
        volumeType: 'gp3'
        volumeEncrypted: true
        volumeKmsKeyID: 'id'
        volumeIOPS: 3000
        volumeThroughput: 125
